image: golang:1.24

variables:
  GOPATH: $CI_PROJECT_DIR/.go

cache:
  paths:
    - .go/pkg/mod/

stages:
  - docs
  - build
  - test

before_script:
  - mkdir -p .go
  - go mod download

verify_docs:
  stage: docs
  tags:
    - aws
  script:
    - go tool tfplugindocs generate --provider-dir . --provider-name hlb
    # Git will show differences between working tree (newly generated docs) and index (committed docs)
    - git diff --exit-code docs/
    # If there are differences, the command will exit with non-zero status, failing the job

unit_tests:
  stage: test
  tags:
    - aws
  script:
    - go test -v $(go list ./... | grep -v /vendor/)

build:
  stage: build
  tags:
    - aws
  script:
    - go build -o terraform-provider-hlb
    - go build -o zonehero ./cmd/zonehero
  artifacts:
    paths:
      - terraform-provider-hlb
      - zonehero
